### ISSUE TITLE
Nested Text's `onPress` property is never called 

### ISSUE THREAD

**Issue by rasom** [status-im/react-native-desktop#343] opened 2018-09-24 06:42 UTC
if nested `Text` component has `onPress` property specified it is not called when text is clicked. `onPress` in parent `Text` component works as expected

`idex.desktop.js`:
```js
import React, {Component} from 'react';
import {
    AppRegistry,
    StyleSheet,
    Text,
    View
} from 'react-native';

function onPress() {
    alert("pressed");
}

class DesktopSampleApp extends Component {
    render() {
        return (
            <View style={styles.container}>
                <Text style={styles.welcome}>
                    Welcome to React Native!
                </Text>
                <Text style={styles.instructions}>
                    To get started, edit
                    <Text style={styles.instructions2}
                          //nested onPress here
                          onPress={onPress}>
                        index.desktop.js
                    </Text>
                </Text>
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5FCFF',
    },
    welcome: {
        fontSize: 20,
        textAlign: 'center',
        margin: 10,
    },
    instructions: {
        textAlign: 'center',
        color: '#333333',
        marginBottom: 5,
    },
    instructions2: {
        textAlign: 'center',
        color: 'green',
        marginBottom: 5,
    }
});

AppRegistry.registerComponent('DesktopSampleApp', () => DesktopSampleApp);
```

**Comment by vkjr** [comment] 2018-09-24 09:47
Duplicate of #290

**Closed** 2018-09-24 11:15 UTC
Labels: bug
